name = "qrise-redirect"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "QR_KV"
id = "397cef7aacbb4efbbd142f84c6009a4e"

[vars]
SUPABASE_URL = "https://ajmtpvxpwerhrlxhrhxs.supabase.co"
APP_URL = "https://your-app.vercel.app"